# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20160621_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
