# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0003_auto_20160622_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
