# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0005_tweet_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='email',
        ),
    ]
